# Generated by Django 3.0.4 on 2020-04-22 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='citizenship_details',
            fields=[
                ('citizenship_id', models.AutoField(primary_key=True, serialize=False)),
                ('citizenship_name', models.CharField(max_length=100)),
                ('citizen_code', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'citizenship_details',
            },
        ),
        migrations.CreateModel(
            name='city_master',
            fields=[
                ('city_id', models.AutoField(primary_key=True, serialize=False)),
                ('city_name', models.CharField(max_length=100)),
                ('country_code', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'city_master',
            },
        ),
        migrations.CreateModel(
            name='corporate_details',
            fields=[
                ('corporate_id', models.AutoField(primary_key=True, serialize=False)),
                ('corporate_name', models.CharField(max_length=100)),
                ('agent_name', models.CharField(max_length=100)),
                ('office_number', models.IntegerField()),
                ('corporate_status', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=2)),
                ('r_citizenship_id', models.ForeignKey(db_column='r_citizenship_id', on_delete=django.db.models.deletion.CASCADE, to='signIn.citizenship_details')),
            ],
            options={
                'db_table': 'corporate_details',
            },
        ),
        migrations.CreateModel(
            name='currency_details',
            fields=[
                ('currency_id', models.AutoField(primary_key=True, serialize=False)),
                ('currency_code', models.CharField(max_length=100)),
                ('currency_display_name', models.CharField(max_length=100)),
                ('currency_status', models.CharField(max_length=2)),
            ],
            options={
                'db_table': 'currency_details',
            },
        ),
        migrations.CreateModel(
            name='group_details',
            fields=[
                ('group_id', models.AutoField(primary_key=True, serialize=False)),
                ('group_alias_name', models.CharField(max_length=20)),
                ('group_name', models.CharField(max_length=100)),
                ('access_group_id', models.CharField(max_length=100)),
                ('active_status', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'group_details',
            },
        ),
        migrations.CreateModel(
            name='status_details',
            fields=[
                ('status_id', models.AutoField(primary_key=True, serialize=False)),
                ('status_code', models.CharField(max_length=10)),
                ('status_name', models.CharField(max_length=100)),
                ('front_end', models.CharField(max_length=100)),
                ('r_group_id', models.ForeignKey(db_column='r_group_id', on_delete=django.db.models.deletion.CASCADE, to='signIn.group_details')),
            ],
            options={
                'db_table': 'status_details',
            },
        ),
        migrations.CreateModel(
            name='user_type_master',
            fields=[
                ('user_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_type_name', models.CharField(max_length=100)),
                ('user_type_status', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'user_type_master',
            },
        ),
        migrations.CreateModel(
            name='wallet_details',
            fields=[
                ('wallet', models.AutoField(primary_key=True, serialize=False)),
                ('wallet_account', models.CharField(max_length=100)),
                ('main_balance', models.IntegerField()),
                ('last_topup_amount', models.IntegerField()),
                ('last_topup_date', models.DateField()),
                ('topup_by', models.IntegerField()),
                ('remarks', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=2)),
                ('r_corporate_id', models.ForeignKey(db_column='r_corporate_id', on_delete=django.db.models.deletion.CASCADE, to='signIn.corporate_details')),
            ],
            options={
                'db_table': 'wallet_details',
            },
        ),
        migrations.CreateModel(
            name='user_details',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('additional_info', models.CharField(max_length=100)),
                ('time_zone', models.CharField(max_length=100)),
                ('created_by', models.CharField(max_length=11)),
                ('created_date', models.DateField(max_length=50)),
                ('updated_by', models.IntegerField(max_length=11)),
                ('status', models.CharField(max_length=10)),
                ('r_corporate_id', models.ForeignKey(db_column='r_corporate_id', on_delete=django.db.models.deletion.CASCADE, to='signIn.corporate_details')),
                ('r_group_id', models.ForeignKey(db_column='r_group_id', on_delete=django.db.models.deletion.CASCADE, to='signIn.group_details')),
                ('r_status_id', models.ForeignKey(db_column='r_status_id', on_delete=django.db.models.deletion.CASCADE, to='signIn.status_details')),
            ],
            options={
                'db_table': 'user_details',
            },
        ),
        migrations.AddField(
            model_name='group_details',
            name='r_user_type_id',
            field=models.ForeignKey(db_column='r_user_type_id', on_delete=django.db.models.deletion.CASCADE, to='signIn.user_type_master'),
        ),
        migrations.AddField(
            model_name='corporate_details',
            name='r_currency_id',
            field=models.ForeignKey(db_column='r_currency_id', on_delete=django.db.models.deletion.CASCADE, to='signIn.currency_details'),
        ),
        migrations.CreateModel(
            name='corporate_branch_details',
            fields=[
                ('corporate_branch_details_id', models.AutoField(primary_key=True, serialize=False)),
                ('branch_name', models.CharField(max_length=100)),
                ('branch_location', models.CharField(max_length=100)),
                ('branch_pincode', models.IntegerField()),
                ('status', models.CharField(max_length=2)),
                ('r_corporate_id', models.ForeignKey(db_column='r_corporate_id', on_delete=django.db.models.deletion.CASCADE, to='signIn.corporate_details')),
                ('r_wallet_id', models.ForeignKey(db_column='r_wallet_id', on_delete=django.db.models.deletion.CASCADE, to='signIn.wallet_details')),
            ],
            options={
                'db_table': 'corporate_branch_details',
            },
        ),
    ]
